### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by TBarregren** [DevelopersToolbox/ini-file-parser#4]
### What happened?

I create an ini file with a _comment_ that looks like a key/value pair where value is missing:

```bash
cat <<EOT > test.ini
[section]
; x = 
y = 2
EOT
```

I source the script and load the ini file:

```bash
source ini-file-parser.sh
process_ini_file test.ini
```

This results in an error message:

```
[ ERROR ] line 2: No value
```

### Expected behavior

I expect the script to ignore line 2 because it is a comment.

### How do we reproduct the bug?

1. Open an terminal.
2. Change the terminal's working directory to `…/ini-file-parser/src`.
3. Copy the above script and paste it into the terminal.

### Relevant log output

```shell
[ ERROR ] line 2: No value
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TGWolf** [comment]
That should now be fixed.

**Comment by TBarregren** [comment]
Beautiful. Thank you.
